Fix for reconnecting bug with launcher
Starystars67/BeamNG-MP pull request #165
Opened 2021-11-10 23:32 UTC by lionkor

This fixes a bug where, after briefly disconnecting, the launcher repeatedly tries to reconnect.

I don't know if this is the same issue as the issue we've been seeing for months, it might be.

2021-11-10 23:38 UTC, lionkor commented
That entire piece of code is super suspect, `git blame` says that @jojos38 added this in 7028ba0f6b23550fd4e8cb2325a3b0ed9cfc8ae2, so maybe he knows why/what/how this is a thing here.

2021-11-11 02:16 UTC, Starystars67 commented
Could have been a mistake? IIRC it was originally declared further up in the file? Either way nice find!

2021-11-11 02:16 UTC, Starystars67 approved these changes

2021-11-11 07:43 UTC, lionkor commented
The missing line for sure, I was more wondering about the entire logic in that block.

2021-11-11 23:24 UTC, 20dka requested changes
This effectively bypasses our "first connection check" system originally put in place so the BeamMP client mod can delete itself if it is being ran without the launcher present.
Instead we should disable the system properly, as it has been found to have been made obsolete.

2021-11-11 23:26 UTC, lionkor commented
> This effectively bypasses our "first connection check" system originally put in place so the BeamMP client mod can delete itself if it is being ran without the launcher present. Instead we should disable the system properly, as it has been found to have been made obsolete.

I didn't see that this effectively disables the entire piece of code, but I see that now. This should not be merged then and instead a proper fix should be implemented.

I agree the entire mod deletion is obsolete and can go.

2022-03-21 10:07 UTC, lionkor commented
I assume the inactivity means this was fixed already or isnt desired, closing

2022-03-21 10:07 UTC, closed without merging