Updates and fixes
Starystars67/BeamNG-MP pull request #232
Opened 2022-08-30 16:03 UTC by snepsnepsnep

2022-09-08 18:44 UTC, 20dka approved these changes

2022-09-08 23:48 UTC, Olrosse approved these changes

2022-09-09 18:36 UTC, Starystars67 commented on lua/ge/extensions/MPVehicleGE.lua
> +	if not players[playerID] then return end -- TODO: better fix?
No, this should do the job :)

2022-09-09 18:40 UTC, Starystars67 commented on lua/ge/extensions/MPCoreNetwork.lua
> +	['Z'] = function(params) launcherVersion = params; end
My only issue here is how does the UI know what the launcher/client version is?
We display this info in the bottom right on the main menu when you click on the game version.

2022-09-09 18:41 UTC, Starystars67 requested changes
Please see the comments I added in my review.

2022-09-09 18:44 UTC, snepsnepsnep commented on lua/ge/extensions/MPCoreNetwork.lua
> +	['Z'] = function(params) launcherVersion = params; end
setClientVersion does not exist anywhere in the JS anymore so it was just throwing an error.
Currently the UI gets the launcher version through the getLauncherVersion() function in MPCoreNetwork.

2022-09-19 18:20 UTC, Starystars67 approved these changes

2022-09-19 18:20 UTC, merged