Add improved sync feature
Starystars67/BeamNG-MP pull request #243
Opened 2022-09-22 02:39 UTC by 20dka

This PR incorporates code from @jacobcargen and mine building a UI around it.

2022-09-22 20:23 UTC, Olrosse approved these changes

2022-09-22 22:20 UTC, Starystars67 approved these changes
Looks good however I have not been able to test, on a code level though it looks good.

2022-09-22 22:30 UTC, 20dka commented
this resolves #228

2022-09-23 00:14 UTC, 20dka commented
todo: move queue button to avoid accidental server leaving

2022-09-23 05:51 UTC, O1LER commented
> todo: move queue button to avoid accidental server leaving

Personally, i would move the quit button, all the way to the left, since quit button and servername are both about the server while event queue has somewhat a connection to players, so itsmore fitting next to the number of players.

Also, is there a keybind to manually load queue? If not, that might be nice too

2022-09-23 19:47 UTC, Mack29446 commented on ui/modules/options/multiplayer.partial.html
> +    <p flex="50"><span class="mp-setting-highlight">NEW</span> {{:: 'ui.options.multiplayer.queueAutoSkipRemote' | translate }}</p>
This is referring to the wrong locale

2022-09-23 19:48 UTC, Mack29446 requested changes

2022-09-23 19:48 UTC, Mack29446 commented on ui/modules/options/multiplayer.partial.html
> +    <p flex="50"><span class="mp-setting-highlight">NEW</span> {{:: 'ui.options.multiplayer.queueAutoSkipRemote' | translate }}</p>
This is also using the wrong locale

2022-09-23 19:48 UTC, Mack29446 commented on ui/modules/options/multiplayer.partial.html
> +    <p flex="50"><span class="mp-setting-highlight">NEW</span> {{:: 'ui.options.multiplayer.queueAutoSkipRemote' | translate }}</p>
This is referring to the wrong locale

2022-09-23 19:48 UTC, Mack29446 commented on locales/en-US.json
> +    "ui.options.multiplayer.queueApplySpeed": "Queue apply speed treshold",
Please fix this typo - it should be `threshold` instead of `treshold`

2022-09-23 19:48 UTC, Mack29446 commented on locales/en-US.json
> +    "ui.options.multiplayer.queueApplyTimeout.tooltip": "You have to move under your set speed treshold for this long before queues apply",
Same typo here

2022-09-23 19:55 UTC, Mack29446 approved these changes
Thank you! LGTM

2022-09-23 19:56 UTC, merged