Update beammp.json
Starystars67/BeamNG-MP pull request #373
Opened 2023-07-23 20:23 UTC by 2PXL

adds function to toggle nametag with a custom bind (part 2)

this also adds a bind to queue events

2023-07-24 20:02 UTC, Starystars67 commented
Hey there, thank you for raising a PR, I notice you mention a part 2, shall we wait for that first before processing your PR?

Thanks

2023-07-24 20:10 UTC, 2PXL commented
> Hey there, thank you for raising a PR, I notice you mention a part 2, shall we wait for that first before processing your PR?
> 
> Thanks

I sent that at the same time

2023-07-24 20:20 UTC, Starystars67 commented
Understood, thank you.
I am just testing the code now, made a small change to fix toggleNametags being null.

2023-07-24 20:29 UTC, Starystars67 commented
Okay I'm out of time for now, If you have the time would you mind looking into the non working event for `playernametags`, it does not work. I tried changing it to `"onDown": "if MPVehicleGE then MPVehicleGE.hideNicknames() end",` however that did not seem to do it for some reason.

2023-07-24 20:56 UTC, 2PXL commented
> Okay I'm out of time for now, If you have the time would you mind looking into the non working event for `playernametags`, it does not work. I tried changing it to `"onDown": "if MPVehicleGE then MPVehicleGE.hideNicknames() end",` however that did not seem to do it for some reason.

I had to press it a couple times before it starts working but ill look into getting it so it works first try

2023-07-24 22:28 UTC, 2PXL commented
if it was giving you errors in console I think you also have to add the code I added to "MPVehicleGE.lua"

2023-07-24 22:47 UTC, O1LER commented
> if it was giving you errors in console I think you also have to add the code I added to "MPVehicleGE.lua"

But you have to add that commit to this PR. If you go to "Files changed" here at the top right, theres only changes made to the beammp.json

2023-07-24 22:49 UTC, O1LER commented
Would be this one b692be8ef88aff4b280d0456cb9b1f1f21222b9b and this 82285cc48000eaa902cdb5a0d5da52ad84bafc8e

2023-07-24 22:53 UTC, 2PXL commented
> Would be this one [b692be8](https://github.com/BeamMP/BeamMP/commit/b692be8ef88aff4b280d0456cb9b1f1f21222b9b) and this [82285cc](https://github.com/BeamMP/BeamMP/commit/82285cc48000eaa902cdb5a0d5da52ad84bafc8e)
> 
> But you got them each in its own branch. You can make a branch for a certain change/feature that you are working on, and this branch can have multiple commits in it. Or you can work directly on your fork of the development branch. Dont know which method ispreferred by beamMP

can I make a branch now with my changes? or should I remember that for next time?

2023-07-24 22:55 UTC, O1LER commented
I think you can move those commits over, either directly into this PR, or into one of the branches you created.
Or, you merge each of your branches into your development branch, then open up a new PR here that merges your development branch into the beamMP one
But i dont know which of those options if the best

2023-07-25 07:54 UTC, Starystars67 commented
> Would be this one [b692be8](https://github.com/BeamMP/BeamMP/commit/b692be8ef88aff4b280d0456cb9b1f1f21222b9b) and this [82285cc](https://github.com/BeamMP/BeamMP/commit/82285cc48000eaa902cdb5a0d5da52ad84bafc8e)
> 
> But you got them each in its own branch. You can make a branch for a certain change/feature that you are working on, and this branch can have multiple commits in it. Or you can work directly on your fork of the development branch. Dont know which method ispreferred by beamMP

The preferred is to use a new "feature" branch under your own fork for new features, and a similar convention for fixes/issues and the likes. That said working on the development branch is also okay since it will be brought in via PR.

2023-07-25 07:56 UTC, Starystars67 commented
> > Would be this one [b692be8](https://github.com/BeamMP/BeamMP/commit/b692be8ef88aff4b280d0456cb9b1f1f21222b9b) and this [82285cc](https://github.com/BeamMP/BeamMP/commit/82285cc48000eaa902cdb5a0d5da52ad84bafc8e)
> > But you got them each in its own branch. You can make a branch for a certain change/feature that you are working on, and this branch can have multiple commits in it. Or you can work directly on your fork of the development branch. Dont know which method ispreferred by beamMP
> 
> can I make a branch now with my changes? or should I remember that for next time?

You did already make a branch, it is called 2PXL:2PXL-patch-1-1. Please do follow O1LER's advice and have all of your work relating to this in one branch so that it will all be a part of the same PR.

2023-07-25 15:13 UTC, 2PXL commented
> > > Would be this one [b692be8](https://github.com/BeamMP/BeamMP/commit/b692be8ef88aff4b280d0456cb9b1f1f21222b9b) and this [82285cc](https://github.com/BeamMP/BeamMP/commit/82285cc48000eaa902cdb5a0d5da52ad84bafc8e)
> > > But you got them each in its own branch. You can make a branch for a certain change/feature that you are working on, and this branch can have multiple commits in it. Or you can work directly on your fork of the development branch. Dont know which method ispreferred by beamMP
> > 
> > 
> > can I make a branch now with my changes? or should I remember that for next time?
> 
> You did already make a branch, it is called 2PXL:2PXL-patch-1-1. Please do follow O1LER's advice and have all of your work relating to this in one branch so that it will all be a part of the same PR.

done, hope that was the correct way.

2023-07-25 17:16 UTC, Starystars67 commented
> done, hope that was the correct way.

Yep, spot on!

2023-07-25 17:24 UTC, Starystars67 requested changes
Once the two changes are made and an in-game test is done I am happy with this to be merged.

Thank you

2023-07-25 17:24 UTC, Starystars67 commented on lua/ge/extensions/MPVehicleGE.lua
> +-- Global variable to keep track of the current state
Please can you comment this according to the format we are using which is ldoc:
https://github.com/lunarmodules/ldoc

2023-07-25 17:24 UTC, Starystars67 commented on lua/ge/extensions/MPVehicleGE.lua
> +local hideNicknames = false
Please move this variable up to be with the rest of our defined variables.

2023-07-25 20:05 UTC, 2PXL commented
should be good now if I understood it correctly.

2023-07-26 10:35 UTC, Starystars67 approved these changes

2023-07-26 10:36 UTC, Starystars67 commented
Hello, I made a couple of small changes, nothing major but all good now.
Thank you for your contribution to the project.

Is there anything else you would like to add before we go ahead and merge this?

2023-07-26 10:36 UTC, Starystars67 approved these changes

2023-07-26 14:40 UTC, 2PXL commented
> Hello, I made a couple of small changes, nothing major but all good now. Thank you for your contribution to the project.
> 
> Is there anything else you would like to add before we go ahead and merge this?

no that is all, thank you.

2023-07-27 09:43 UTC, Starystars67 commented
Awesome, Thank you for your contribution towards this!
If you @ me (Titch) in the BeamMP Discord and DM me on our forum I will drop you the contributor roles so you can join the rest of the team.

2023-07-27 09:43 UTC, merged