Launcher v2.1 compat
Starystars67/BeamNG-MP pull request #374
Opened 2023-07-24 18:26 UTC by Starystars67

2023-07-24 20:01 UTC, Starystars67 commented
This has all been confirmed working and tested with both launcher v2.0.X and v2.1.
Players I tested with reported no issues in playing with me.

2023-07-24 21:15 UTC, OfficialLambdax requested changes
Please provide the v2.1 launcher. Cannot test without

2023-07-24 21:23 UTC, OfficialLambdax commented
Wrong milestone lmao. Why is this 4.9? 4.8 is not Stable yet, isnt this just a 4.8 combat with launcher 2.1?

2023-07-24 21:25 UTC, OfficialLambdax commented on lua/ge/extensions/MPCoreNetwork.lua
> +	-- First check if we are V3 Networking or not
V2.1 Networking

2023-07-24 21:25 UTC, OfficialLambdax commented on lua/ge/extensions/MPCoreNetwork.lua
> +	if not MP then -- This is not required in V3
V2.1

2023-07-25 08:15 UTC, Starystars67 commented
> Please provide the v2.1 launcher. Cannot test without

Launcher is available in the Contributor chat and was shared with the staff team previously too.

> Wrong milestone lmao. Why is this 4.9? 4.8 is not Stable yet, isnt this just a 4.8 combat with launcher 2.1?

This is 4.9 because it is not a patch version change. This is a series of changed that is quite substantive. It would have been a major version change but then I modified it further to be backwards compatible.

2023-07-25 09:56 UTC, Starystars67 commented on lua/ge/extensions/MPCoreNetwork.lua
> +	-- First check if we are V3 Networking or not
This has now been fixed, thank you.
This happened because it was going to end up being a V3 but then we held back some other work for the time being.

2023-07-25 12:54 UTC, OfficialLambdax approved these changes
This works well on my side, no errors no runtime issues and i also dont see any code errors with either v2.0 or v.2.1. Someone may want to make long runtime tests, also on servers that are heaviely scripted like CaRP.

Only issues i see is that the server list is requested three times and that switching between servers while in one, is causing issues with mod loading. But those two have nothing todo with this compat.

2023-08-12 16:59 UTC, merged