Added comments to codebase
Starystars67/BeamNG-MP pull request #377
Opened 2023-07-25 10:09 UTC by Starystars67

This PR adds comments to the majority of the codebase according to Ldoc. 
This works with the GitHub action to automatically deploy this to a GitHub pages documentation site located here:
https://beammp.github.io/BeamMP/

2023-07-25 10:21 UTC, OfficialLambdax commented
MPVehicleGE can be checked

2023-07-25 13:06 UTC, Starystars67 commented
> MPVehicleGE can be checked

This is the depth that I am talking about that I have not done as yet on the other files. 
That said it looks to only be partially completed so far. If you are okay finishing it then please feel free to commit to this branch otherwise I will continue it when I get around to this file.

2023-07-25 13:29 UTC, OfficialLambdax commented
Oh wait right, only the public api was documented

2023-07-25 14:04 UTC, Starystars67 commented
> Oh wait right, only the public api was documented

Yeah, I commented every function that way if someone is wanting to contribute they will have a better idea of what is going on. 
For those looking to write mods to work with BeamMP, this is not the documentation they should use. They should use the likes of our Wiki for that.

2023-11-07 13:10 UTC, OfficialLambdax commented on lua/ge/extensions/MPCoreNetwork.lua
> +		return "2.0" --launcherVersion
Any specific reason for the double tab here and in other functions?

2023-11-07 13:43 UTC, OfficialLambdax requested changes
Just ran the definitions through the ldoc parser and commented where it errors and how to fix it

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/MPConfig.lua
> +-- @tparam string The users nickname that we have received.
@tparam string **x** The users nickname that we have received.

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/MPCoreNetwork.lua
> +--- @returns currentServer table
@return~~s~~ currentServer table

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/MPCoreNetwork.lua
> +--- @usage `MPCoreNetwork.setCurrentServer('localhost', 30814, 'Test Server')`
@usage `MPCoreNetwork.setCurrentServer('localhost', 30814, 'Test Server')`
dont use `. it ruins the formating of the example in ldoc

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/MPGameNetwork.lua
>  -------------------------------------------------------------------------------
ldoc thinks this is a function documentation and then cannot parse the next doc. Solution is to make a space behind the second --
so that `-------------------------------------------------------------------------------`
becomes `-- -----------------------------------------------------------------------------`

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/MPGameNetwork.lua
>  -------------------------------------------------------------------------------
same

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/MPGameNetwork.lua
> +-- @tparam integer delta time
-- @tparam integer **dt** delta time

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/MPHelpers.lua
> +--- ?
please just --. ldoc errors with ---

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/UI.lua
>  ---------------------------------------------------------------
same. space after -- otherwise ldoc fails

2023-11-07 13:43 UTC, OfficialLambdax commented on lua/ge/extensions/multiplayer/ui/options.lua
>  --------------------------------
same. space after --. otherwise ldoc fails

2023-11-07 14:45 UTC, Starystars67 commented on lua/ge/extensions/MPCoreNetwork.lua
> +		return "2.0" --launcherVersion
Hmm this is odd, I am not sure why that has happened, Maybe I caught a shortcut or something that attempted to format it or something. :/

2023-11-07 14:56 UTC, Starystars67 commented
> Just ran the definitions through the ldoc parser and commented where it errors and how to fix it

Possibly so, I was working in accordance to lua-language-server for vs-code standard which did look to be compatible / the same as ldoc standard.

Running the build process for the docs (ldoc) it does look to have worked with both of our examples. See the latest files on this branch: https://github.com/BeamMP/BeamMP/tree/gh-pages and then download to view them in your browser.

This may  need more looking into.

2023-11-07 15:24 UTC, OfficialLambdax submitted a review, later dismissed
Ok i read over the docs and made some fixes and doc changes

2023-11-13 16:05 UTC, Starystars67 commented
Are we ready and okay with this being merged now?

2023-11-13 17:29 UTC, OfficialLambdax commented
yes

2023-11-16 09:39 UTC, OfficialLambdax approved these changes

2023-11-16 09:40 UTC, merged