Added text to the login page
Starystars67/BeamNG-MP pull request #397
Opened 2023-10-27 12:34 UTC by 1eob

Added a simple temporary fix for the register button not working by adding instructions on how to register on the login page

![image](https://github.com/BeamMP/BeamMP/assets/87150088/dc7ce036-2549-4abb-b1d2-fbf1954f2b82)

2023-10-27 12:50 UTC, OfficialLambdax requested changes

2023-10-27 12:50 UTC, OfficialLambdax commented on ui/modules/multiplayer/login.partial.html
> +					<md-button class="button" onclick="openExternalLink('https://forum.beammp.com/signup')">{{:: 'ui.multiplayer.register' | translate}}</md-button>
What happens if you comment out the Register Button?

2023-10-27 14:19 UTC, 1eob commented on ui/modules/multiplayer/login.partial.html
> +					<md-button class="button" onclick="openExternalLink('https://forum.beammp.com/signup')">{{:: 'ui.multiplayer.register' | translate}}</md-button>
I mean i can certainly try. im still heavily learning so i dont want to do something that might break another thing

2023-10-27 14:22 UTC, 1eob commented on ui/modules/multiplayer/login.partial.html
> +					<md-button class="button" onclick="openExternalLink('https://forum.beammp.com/signup')">{{:: 'ui.multiplayer.register' | translate}}</md-button>
Actually it looks fine the ui has seem to adjust automatically 

![image](https://github.com/BeamMP/BeamMP/assets/87150088/e435ef6e-6b6c-49a4-97d5-16a984474810)

2023-10-27 14:37 UTC, OfficialLambdax approved these changes

2023-10-27 14:38 UTC, OfficialLambdax commented on ui/modules/multiplayer/login.partial.html
> +					<md-button class="button" onclick="openExternalLink('https://forum.beammp.com/signup')">{{:: 'ui.multiplayer.register' | translate}}</md-button>
push that change to your fork pls

2023-10-27 15:10 UTC, 1eob commented on ui/modules/multiplayer/login.partial.html
> +					<md-button class="button" onclick="openExternalLink('https://forum.beammp.com/signup')">{{:: 'ui.multiplayer.register' | translate}}</md-button>
Done

2023-10-27 16:04 UTC, OfficialLambdax approved these changes

2023-11-01 20:28 UTC, Starystars67 approved these changes
This does indeed work as a stop-gap until the EA launcher moves to public.

Thank you @1eob

2023-11-01 20:29 UTC, merged

2023-11-02 20:13 UTC, 1eob commented
> This does indeed work as a stop-gap until the EA launcher moves to public.
> 
> Thank you @1eob

Np ik it's small but it's a start for looking into the code

2023-11-03 15:29 UTC, Starystars67 commented
> > This does indeed work as a stop-gap until the EA launcher moves to public.
> > Thank you @1eob
> 
> Np ik it's small but it's a start for looking into the code

I completely agree :)