Featured & Partner Server Tabs
Starystars67/BeamNG-MP pull request #403
Opened 2023-11-05 01:31 UTC by Starystars67

This PR adds the Featured and Partnered servers tabs into the multiplayer menu.

The locales are also included but were generated using Google translate so may be contextually incorrect.

Also removed the second German translation as it appeared to be out of date.

2023-11-05 09:42 UTC, OfficialLambdax commented on ui/modules/multiplayer/multiplayer.js
> +			console.log(server)
leftover debug information?

2023-11-05 13:31 UTC, Starystars67 commented on ui/modules/multiplayer/multiplayer.js
> +			console.log(server)
Haha, yep, good spot thank you.

2023-11-05 17:35 UTC, OfficialLambdax requested changes
Still need to test it

2023-11-05 17:35 UTC, OfficialLambdax commented on ui/modules/multiplayer/multiplayer.js
> +		console.log(featured)
debug info

2023-11-06 09:59 UTC, Starystars67 commented on ui/modules/multiplayer/multiplayer.js
> +		console.log(featured)
Thank you, fixed too :)

2023-11-08 15:37 UTC, Starystars67 commented
> Still need to test it

Please could you test and confirm functionality for yourself too, Just as a sanity check for me at least.

2023-11-08 15:44 UTC, OfficialLambdax commented
The featured server tab is empty and the partnered server tab is broken. Thats what happens when i click it
![fghjfgghjghjkghj](https://github.com/BeamMP/BeamMP/assets/91626975/1bb8e039-5dca-458c-ae9b-c4cb671cdbf1)

2023-11-08 15:45 UTC, Starystars67 commented
> The featured server tab is empty and the partnered server tab is broken. Thats what happens when i click it ![fghjfgghjghjkghj](https://user-images.githubusercontent.com/91626975/281460408-1bb8e039-5dca-458c-ae9b-c4cb671cdbf1.png)

Just to confirm you cleared cache and reloaded the UI?

2023-11-08 15:47 UTC, OfficialLambdax commented
Yes i did.. no errors, no nothing

2023-11-08 15:48 UTC, Starystars67 commented
Odd, okay thank you.

Will load it up again my side and see if I can replicate.

2023-11-13 16:04 UTC, Starystars67 commented
Now fixed.

Featured Servers:
<img width="1276" alt="image" src="https://github.com/BeamMP/BeamMP/assets/15389482/2327b6d0-55d7-43ae-89dd-9e02b47b2f83">

Partner Servers:
<img width="1149" alt="image" src="https://github.com/BeamMP/BeamMP/assets/15389482/bb77f854-87f6-490e-8a5a-626db5d01174">

If someone could please retest to confirm :)

2023-11-16 10:18 UTC, OfficialLambdax approved these changes
Appears to be working as intended

2023-11-16 10:55 UTC, merged