Beamlings V1
Starystars67/BeamNG-MP pull request #404
Opened 2023-11-06 19:51 UTC by VanilleVaschnille

First version of the "Beamling" unicycle, an addon for BeamMP wich adds a custom character model to the unicycle.
![image](https://github.com/BeamMP/BeamMP/assets/150075711/33ec91a5-7904-4348-81c2-951d1d70493e)

2023-11-07 15:41 UTC, OfficialLambdax requested changes

2023-11-07 15:41 UTC, OfficialLambdax commented on vehicles/unicycle/main.materials.json
is missing the game own materials. therefore rendering the game own configurations texture less. can be solved by merging the two materials together

2023-11-13 18:14 UTC, VanilleVaschnille commented on vehicles/unicycle/main.materials.json
Fixed.

2023-12-03 22:42 UTC, Starystars67 commented
Due to licensing issues this will be closed now.

Work will be incorporated as agreed via alternative means.

2023-12-03 22:42 UTC, closed without merging