Lua side Beamlings support
Starystars67/BeamNG-MP pull request #405
Opened 2023-11-07 01:36 UTC by OfficialLambdax

Autosaves the custom beamling upon deletion of the beamling. Yet to be discussed if this is the desired way todo this

2023-11-07 10:32 UTC, Starystars67 commented
I wonder could this assist with it for you?

https://github.com/BeamMP/BeamMP/blob/development/lua/ge/extensions/multiplayer/multiplayer.lua#L21

I notice that there is a `getPlayerUnicycle()` so maybe a custom implementation of this would be a good idea?

2023-12-06 11:15 UTC, Starystars67 commented
This PR needs the accompanying lua side of the functionality to complete this.

This is a requirement for the 4.10.0 update.

2023-12-06 11:24 UTC, Starystars67 commented
Sample of the options in the UI as default:
<img width="446" alt="image" src="https://github.com/BeamMP/BeamMP/assets/15389482/34416ab4-e7dc-4ad1-8eb7-49dbbc6eee58">

2023-12-10 22:29 UTC, OfficialLambdax commented
Introduces two Options within the Multiplayer Options.
1. A Selector for Unicycle configs (the user here can choose their default unicycle config)
> Please test. Upon choosing a new config, the entry will vanish and a small text will appear on the top right indicating that the new default has been set.
2. A Option to automatically save the latest used unicycle config upon despawning it.
> Please test. Is at default turned off. Will only work in a multiplayer server.

The default unicycle config is saved under `userdata/vehicles/unicycle/beammp_default.pc`. If no such file exists, beammp's own default is spawned. The default is a beamling config. Beamlings are not part of beammp. therefore it wont be able to spawn a beamling and will probably spawn the no mesh variant (didnt test myself).

2023-12-10 22:38 UTC, lionkor commented
Please @ reviewers keep in mind a review includes testing on a server

2023-12-12 21:56 UTC, Starystars67 commented
I tested this just now, made a custom config and saved it as santa however I do not see it in the list, Am I missing something?
<img width="1288" alt="image" src="https://github.com/BeamMP/BeamMP/assets/15389482/7ca796df-4b00-4ecb-acf2-0e1d8e93fcdb">

2023-12-12 22:01 UTC, OfficialLambdax commented
Also made a custom config and named it Santa. Directly opened the multiplayer options after and got that entry
![jhghjgjkghjghj](https://github.com/BeamMP/BeamMP/assets/91626975/27575feb-da77-4e80-9a67-31f32f7fef92)

2023-12-13 14:53 UTC, Starystars67 requested changes
Tested in-game and working as expected.
Needs some commenting added but otherwise good to go!

2023-12-13 14:53 UTC, Starystars67 commented on lua/ge/extensions/MPConfig.lua
> +local function getUnicycleConfigs()
Please can comments / documentation be added to this function.
Keeps the codebase consistent.

2023-12-13 14:53 UTC, Starystars67 commented on lua/ge/extensions/MPConfig.lua
> +local function setDefaultUnicycle(configFileName)
Please can comments / documentation be added to this function.
Keeps the codebase consistent.

2023-12-13 14:53 UTC, Starystars67 commented on lua/ge/extensions/MPConfig.lua
> +local function onSettingsChanged()
Please can comments / documentation be added to this function.
Keeps the codebase consistent.

2023-12-16 20:58 UTC, Starystars67 approved these changes

2023-12-16 20:58 UTC, merged