fix favorite servers with single quotes in name or desc
Starystars67/BeamNG-MP pull request #407
Opened 2023-11-21 14:31 UTC by Trezub

fixes #290

2023-11-21 16:26 UTC, KauamCosta commented
Approve

2023-11-21 17:38 UTC, OfficialLambdax requested changes
This breaks the favorite feature entirely. The receiving end cannot process the encoded json.
![fgdgdfgfdgdfgdffgd](https://github.com/BeamMP/BeamMP/assets/91626975/a0a9c9d9-3493-418d-9620-989a4c775fd6)

2023-11-21 17:38 UTC, OfficialLambdax commented on ui/modules/multiplayer/multiplayer.js
> +	bngApi.engineLua(`MPConfig.setFavorites('${JSON.stringify(favorites).replace(/'/g, "\\'")}')`);
if you so choose to encode json you also have to decode it on the receiving end. that being in MPConfig.setFavorites()

2023-11-22 12:40 UTC, Starystars67 commented
Interesting that this is raised shortly after I already started working on this one :P

https://github.com/BeamMP/BeamMP/tree/fix-290

2023-11-25 08:52 UTC, closed without merging