add handling for simple traffic parts that doesnt exist
Starystars67/BeamNG-MP pull request #488
Opened 2024-01-08 06:15 UTC by Please-Pick-a-Name

before this, when the simple vehicle option is turned on, and if there is an entry in simplified_vehicles for the vehicle, it will attempt to replace the body slot of said vehicle to the simple traffic body
regardless if the part actually exist:
- instead of the original body, vehicles end up with the default body, if the part doesn't exist or not valid
added bonus:
since the recent beamng update, the naming convention for the simple traffic parts have changed, that means:
- all vehicles, include the one with the simple traffic variant, will have their body changed to default body

i want to fix it so it check if the part exists and the slot matches, and i want to update the list in simplified_vehicles

so far i have done the existence check, but idk how to test it, someone plz tell me beammp deving workflow

2024-01-08 08:34 UTC, Please-Pick-a-Name commented
it should now check both if the part exist, and if the part's slot type matches/contains where it is expected to fit in
also updated the simplified_vehicles list
didnt test, dunno how to test

2024-01-10 03:40 UTC, Please-Pick-a-Name commented
fixed title cause i cannot english

2024-01-14 12:08 UTC, Please-Pick-a-Name commented
ik how to test my pr now...
yes it errored out, fixing rn

2024-01-14 13:20 UTC, Please-Pick-a-Name commented
actually figured out beammp contribute workflow, this "works_on_my_machine.txt"
thanks o1ler

2024-01-31 08:10 UTC, Starystars67 submitted a review, later dismissed
Testing this I had no errors or issues.
Thank you

2024-02-08 15:23 UTC, Please-Pick-a-Name commented
dead pr kewk

2024-03-02 20:05 UTC, 20dka requested changes

2024-03-02 20:05 UTC, 20dka commented on lua/ge/extensions/MPVehicleGE.lua
> +	if settings.getValue("simplifyRemoteVehicles") then
Could you extract the contents of the if check to a separate function to avoid duplicated code?

2024-03-02 20:05 UTC, 20dka commented on lua/ge/extensions/MPVehicleGE.lua
> +			local slotMap=jbeamIO.getAvailableSlotMap(ioCtx) -- slots2 compatible, maybe theres better way then require jbeamio and let it load the files again...
```suggestion
			local slotMap = jbeamIO.getAvailableSlotMap(ioCtx) -- slots2 compatible, maybe theres better way then require jbeamio and let it load the files again...
```
Please leave whitespace around assignment statements. Do this everywhere in your code

2024-03-03 07:27 UTC, Please-Pick-a-Name commented on lua/ge/extensions/MPVehicleGE.lua
> +	if settings.getValue("simplifyRemoteVehicles") then
sure, its now in vehicleGetSimplified instead

2024-03-03 07:28 UTC, Please-Pick-a-Name commented on lua/ge/extensions/MPVehicleGE.lua
> +			local slotMap=jbeamIO.getAvailableSlotMap(ioCtx) -- slots2 compatible, maybe theres better way then require jbeamio and let it load the files again...
done

2024-03-03 15:14 UTC, 20dka approved these changes

2024-03-03 16:23 UTC, merged