revised input syncing and added support for custom inputs
Starystars67/BeamNG-MP pull request #561
Opened 2024-05-15 20:05 UTC by Olrosse

pretty much a rewrite of the input syncing code to support custom inputs and to make steering more responsive

changed steering input filter to direct and instead added temporal smoothing to every input, seems a lot more accurate and more responsive than using the pad filter, it does however add a bit of latency to inputs that where already using direct filtering

disabled local inputs on the remote vehicles so ghost controlling is no longer possible

changed gear sync to send the current gear with any input change so if a queue is spawned late it will sync as soon as there is any input

2024-05-16 17:59 UTC, OfficialLambdax requested changes
## Problem
About `if a queue is spawned late it will sync as soon as there is any input`
Issue is this
1. Remote player spawned vehicle (i kept it in the quo)
2. They changed to second gear and pressed the clutch
3. I quod
4. I tabbed to their vehicle and could see the gear being in the second but the vehicle was stalled, no clutch input was applied


## This pr changes the packet protocol
### Current format
```
  [c] = float
  [g] = int/string
  [t] = float
  [s] = float
  [b] = float
  [p] = float
```
It only sends each key over this protocol when there has been any update to it

### This PR's format
```
  [throtte] = table
    [state] = float
  [brake] = table
    [state] = float
  [steering] = table
    [state] = float
  [clutch] = table
    [state] = float
  [parkingbrake] = table
    [state] = float
```
The transmitted contents are similiar to the old, but it keeps sending the gear index with every inputs update even when the gear has not changed

## Summary
I think the new system should match the protocol of the old as in the packets contents, aka "steering" gets translated to "s" to reduce packet size

2024-05-16 17:59 UTC, OfficialLambdax commented on lua/vehicle/extensions/BeamMP/MPInputsVE.lua
> +				inputsToSend[inputName] = {state = state}
is this nesting necessary?
eg. `"steering":{"state":-0.172}`. why not just `"s":-0.172`?

2024-05-16 17:59 UTC, OfficialLambdax commented on lua/vehicle/extensions/BeamMP/MPInputsVE.lua
> +	 -- Old sync, keeping for temporary cross compatibility --
How temporary? im thinking of just disabling/removing the old code and make the new match the old format

2024-05-16 17:59 UTC, OfficialLambdax commented on lua/vehicle/extensions/BeamMP/MPInputsVE.lua
> +				diffrence = 0
This typo in `diffrence` instead of `difference` is used multiple times in this pr, tho in `onReset()` this key is named `inputData.difference`

2024-05-17 15:57 UTC, Olrosse commented on lua/vehicle/extensions/BeamMP/MPInputsVE.lua
> +				inputsToSend[inputName] = {state = state}
no not really, the only reason it's there is because i first included the filter as well and after removing that it was convenient to just check for table on receiving end instead of checking for every of the old names, but i can change it to just using the old names, though any custom input from mods will of course have to use their actual input name cause we would have no idea what the input name would be

2024-05-17 15:58 UTC, Olrosse commented on lua/vehicle/extensions/BeamMP/MPInputsVE.lua
> +	 -- Old sync, keeping for temporary cross compatibility --
yep can do that, it's only there so it sync across this build and the current public build, i was gonna remove it as soon as this is in public

2024-05-17 16:04 UTC, OfficialLambdax commented on lua/vehicle/extensions/BeamMP/MPInputsVE.lua
> +	 -- Old sync, keeping for temporary cross compatibility --
Yes i see tho as soon as this pr is merged and a new release is build, it would automatically be shipped to everyone. So the cross compatibility is really not necessary.

2024-05-17 16:05 UTC, OfficialLambdax commented on lua/vehicle/extensions/BeamMP/MPInputsVE.lua
> +				inputsToSend[inputName] = {state = state}
`though any custom input from mods will of course have to use their actual input name cause we would have no idea what the input name would be` yes so we only want to translate the common inputs, eg steering, braking etc. Really clever idea btw to just attach custom inputs

2024-05-17 16:09 UTC, OfficialLambdax commented
### Todo
- [ ] Translate common inputs to shortend versions eg. `steering` -> `s`
- [ ] Remove nesting eg. `"s":{state:0.111}` ->`"s":0.111`
- [ ] Remove cross compatibility code
- [ ] Fix typo

2024-05-22 21:03 UTC, OfficialLambdax reviewed
PR and Changes work as expected, thank you @Olrosse and @stefan750. Will perform a more sorrow test within a competitive community to see how well it runs given varying ping and game lag. Just to see if this pr makes it worse.

2024-06-01 18:11 UTC, lionkor commented
Could we possibly get this tested without an event, or just earlier in general?

2024-06-06 14:50 UTC, Starystars67 commented
@OfficialLambdax any update on this?
Thanks

2024-06-29 18:25 UTC, Starystars67 approved these changes

2024-06-29 18:26 UTC, merged