changed the way we get the colors on vehicle spawn
Starystars67/BeamNG-MP pull request #576
Opened 2024-07-03 00:45 UTC by Olrosse

using getField had issues where the base color could return as nil, this should hopefully fix that by using getMetallicPaintData and veh.color, veh.colorPalette etc instead.

I also removed a duplicate of getObjectByID

2024-07-03 13:21 UTC, OfficialLambdax requested changes

2024-07-03 13:21 UTC, OfficialLambdax commented on lua/ge/extensions/MPVehicleGE.lua
> +		vehicleTable.vcf.paints[3] = createVehiclePaint(veh.colorPalette1, metallicPaintData[3])
I think this should be refactored into the `MPHelpers.getColorsFromVehObj()` function. Point is that atleast one more pr is building on top of it #560

2024-07-03 14:33 UTC, Olrosse commented on lua/ge/extensions/MPVehicleGE.lua
> +		vehicleTable.vcf.paints[3] = createVehiclePaint(veh.colorPalette1, metallicPaintData[3])
I'll change it once I'm on, i was originally thinking we could just do the same for that PR as well but yeah having it as one function makes more sense

2024-07-03 16:45 UTC, OfficialLambdax commented
Tests
- [ ] Spawn a vanilla config with its default color
- [ ] Spawn a vanilla config with a custom preconfigured color
- [ ] Spawn a vanilla config with a entirely custom color
- [ ] Edit into a vanilla config with its default color
- [ ] Edit into a vanilla config with a custom preconfigured color
- [ ] Edit into a vanilla config with a entirely custom color
- [ ] Spawn a snowman unicycle
- [ ] Spawn a custom config with its default color
- [ ] Spawn a custom config with a custom preconfigured color
- [ ] Spawn a custom config with a entirely custom color
- [ ] Edit into a custom config with its default color
- [ ] Edit into a custom config with a custom preconfigured color
- [ ] Edit into a custom config with a entirely custom color
- [ ] 1) Spawn vanilla config with default color 2) Edit to the same vehicle but with a custom config

2024-07-03 22:07 UTC, SaltySnail commented
The unmarked tests don't work in vanilla beamng for certain configs, but the colors are the same between clients.

2024-07-04 00:22 UTC, OfficialLambdax approved these changes
Approving and merging on the basis of the test results from the two dev team members. Can confirm that the missing checkmarks are based on game issues.

Thanks @Olrosse for the pr. Thanks @SaltySnail for helping in testin (:

2024-07-04 00:22 UTC, merged