centred nametags and fixed spectator nametags not being cleared
Starystars67/BeamNG-MP pull request #579
Opened 2024-07-05 19:18 UTC by Olrosse

Currently the name tags are placed 2 meters above the ref node for every vehicle, Here I've moved them to the center of the vehicle 20 cm above the top of the bounding box.
#
Before
![screenshot_2024-07-04_22-16-35](https://github.com/BeamMP/BeamMP/assets/10835721/2171fdbe-0351-4735-a9e3-ae225871a656)
After
![screenshot_2024-07-04_22-15-21](https://github.com/BeamMP/BeamMP/assets/10835721/25bb043e-f7e4-43ec-a140-97292251d2b4)
#
I've also fixed the bug where spectator tags would stay if you cloned or spawned a car while being tabbed to someone else, this happened because the onVehicleSwitched function runs before the vehicle exists in the vehicle map, to fix this i moved the code that sends the active vehicle into it's own function, And then call it when the car is added to the vehicle map if you are tabbed to it.

2024-07-06 07:08 UTC, Starystars67 commented
Woah!

2024-07-16 17:55 UTC, Starystars67 requested changes

2024-07-16 17:55 UTC, Starystars67 commented on lua/ge/extensions/MPVehicleGE.lua
> +        		v.position = vec3(tempPosx,tempPosy,tempPosz)
Indenting mistake :P

2024-08-08 10:05 UTC, Starystars67 approved these changes
Pending a final test this is good to go!

2024-08-08 11:03 UTC, WiserTixx approved these changes
Works as expected

2024-08-08 11:20 UTC, merged