Add Favorite button to the Direct connect tab
Starystars67/BeamNG-MP pull request #608
Opened 2024-08-28 11:53 UTC by purifiedfr

Yet unfinished:
* Localization ~~is not yet implemented tested (I'd appreciate help with this, I don't want to mess anything up)~~ seems to work for English (implemented under `ui.multiplayer.favorite`)
* The button should give feedback when one clicks it
* Custom favorited servers currently show "undefined" for the map (as shown below), further testing is needed

## Screenshots / POCs:
![image](https://github.com/user-attachments/assets/c5cc1ccd-3fe9-4378-b76a-5c093aac3717)
![image](https://github.com/user-attachments/assets/d5987aa3-5ccd-4792-8698-fdf3f588fb8c)

2024-10-12 18:23 UTC, WiserTixx commented
Regarding your points:
- The custom favorited servers show the map as undefined because the client doesn't know anything about the server until it connects, however this is being worked on. There's nothing that can be done about that in this PR.
- The localizations looks good, however it may be clearer to the user if it says something like "Save as favorite". Once this is merged it can be translated into more languages later.
- For the visual feedback maybe show a toast message? `toastr.info`

Codewise it looks good mostly.
The empty `ng-class=""` should be able to be removed.
And could the core functionality of `vm.addCustomServer` and `vm.directConnectFavorite` maybe be merged into a function (`addCustomFavorite` or something)? Then call it via `directConnectFavorite` and `dialogFavorite`.

2024-10-18 17:27 UTC, WiserTixx requested changes

2024-10-18 17:27 UTC, WiserTixx commented on mp_locales/en-US.json
> +    "ui.multiplayer.favorited_toast_description": "This server has been favorited.",
```suggestion
    "ui.multiplayer.favoritedToast.title": "Favorited server",
    "ui.multiplayer.favoritedToast.description": "This server has been favorited.",
```
Suggestion to keep the casing consistent

2024-10-18 17:27 UTC, WiserTixx commented on ui/modules/multiplayer/multiplayer.js
> +		toastr.info($filter('translate')('ui.multiplayer.favorited_toast_description'), $filter('translate')('ui.multiplayer.favorited_toast_title'));
```suggestion
		toastr.info($filter('translate')('ui.multiplayer.favoritedToast.description'), $filter('translate')('ui.multiplayer.favoritedToast.title'));
```

2024-10-18 17:27 UTC, WiserTixx commented on ui/modules/multiplayer/multiplayer.js
> +		addFav(server)
```suggestion
		favorites = await getFavorites();
		addFav(server)
```
This prevents the favorites being cleared when you add a server but haven't loaded the favorites tab yet.

2024-10-20 11:32 UTC, purifiedfr commented
Thank you for these changes

2024-10-20 11:57 UTC, WiserTixx commented
If you're ready for this PR to be reviewed, please mark it so.

2024-10-20 15:50 UTC, purifiedfr commented
It's ready for review

2024-10-20 16:45 UTC, WiserTixx approved these changes

2024-10-26 18:11 UTC, merged