Notification improvements
Starystars67/BeamNG-MP pull request #613
Opened 2024-09-07 20:22 UTC by WiserTixx

Add icons to ui notifications/message and adds a category to all ui notifications to avoid them overwriting another. Also adds a new packet "N" which allows for custom notifications with category and icon

2024-09-07 20:49 UTC, 20dka requested changes

2024-09-07 20:49 UTC, 20dka commented on lua/ge/extensions/MPGameNetwork.lua
>  	['L'] = function(params) UI.showNotification(params) end, -- Display custom notification
please update the comment to signal that this packet is only used for Leaving users
maybe even extract the string matching related to this from `showNotification`, to its own function

2024-09-07 20:49 UTC, 20dka commented on lua/ge/extensions/MPGameNetwork.lua
> +	['N'] = function(params) local category, icon, message = packet:match("([^:]+):([^:]+):(.+)") UI.showNotification(message, category, icon) end,
please add a comment describing the packet type
```suggestion
	['N'] = function(params) local category, icon, message = packet:match("([^:]+):([^:]+):(.+)") UI.showNotification(message, category, icon) end, -- Custom UI notification
```

2024-09-07 20:49 UTC, 20dka commented on lua/ge/extensions/MPVehicleGE.lua
> +        UI.showNotification(''..vehicles[serverVehID].ownerName..'\'s '..vehicles[serverVehID].jbeam..' hasnt been deleted yet?', ''..serverVehID..'delete', 'warning')
please fix the typo "hasnt" -> "hasn't"

2024-09-07 20:49 UTC, 20dka commented on lua/ge/extensions/MPVehicleGE.lua
> +    UI.showNotification('Trying to respawn '..playerOwnerName..'\'s '..vehicles[serverVehID].jbeam, ''..playerOwnerName..''..serverVehID..'respawn', 'directions_car')
optional: please switch the string to `""` if it contains a `'` character, using `\'` is not preferred

2024-09-07 20:49 UTC, 20dka commented on lua/ge/extensions/UI.lua
> +		MPVehicleGE.onPlayerLeft(leftName)
consider extracting this section from this function, since we know it comes from a single source, the `L` packet

2024-09-13 08:16 UTC, Starystars67 submitted a review, later dismissed
LGTM though not tested.

2024-09-15 15:00 UTC, Starystars67 approved these changes, later dismissed

2024-09-15 15:17 UTC, 20dka approved these changes

2024-09-15 15:18 UTC, merged