little changed UI, and add localization
Starystars67/BeamNG-MP pull request #673
Opened 2024-12-13 02:57 UTC by csv4211

changed the design a little, in some places there were problems with the UI since the width of some elements is fixed and less than the width of the text from the localization, and some missing localizations were added,
photos are in order 1 2 (1 - before, 2 - after)
before
![image](https://github.com/user-attachments/assets/e30b7a79-0cd4-4ab8-b4ab-c9520c63be0a)
after
![image](https://github.com/user-attachments/assets/d108b9e8-b555-4888-88ea-bac22fd93dbd)
before
![image](https://github.com/user-attachments/assets/fb38ba5d-8687-4eb7-ad45-2aebeb50cc4b)
after
![image](https://github.com/user-attachments/assets/c7542674-7b00-4282-9cb7-086ea9ae74e7)
before
![image](https://github.com/user-attachments/assets/abbb8fa6-a5b1-4045-b15b-47cf020d5066)
after
![image](https://github.com/user-attachments/assets/f7e2ca17-c121-43fe-8154-69ee266b1360)
before
![image](https://github.com/user-attachments/assets/5b27e17e-c8ef-42db-8e5d-7d5f45b51fc7)
after
![image](https://github.com/user-attachments/assets/3072e3da-1864-4850-ba32-6124da24d1b6)
before
![image](https://github.com/user-attachments/assets/cb1671db-40b6-4bc4-8336-e928d0580679)
after
![image](https://github.com/user-attachments/assets/4762f85d-50d9-4307-903c-fad51558f5af)

2024-12-13 10:06 UTC, WiserTixx commented on mp_locales/ru_RU.json
> +  "ui.multiplayer.add.favorite": "Сохранить в избранное",
Could you instead add a translation for `ui.multiplayer.add.favorite` and not add one that is not present anywhere else?

2024-12-13 10:15 UTC, WiserTixx requested changes

2024-12-13 10:15 UTC, WiserTixx commented on mp_locales/ru_RU.json
> +  "ui.multiplayer.add.favorite": "Сохранить в избранное",
Could you instead add a translation for `ui.multiplayer.add.favorite` and not add one that is not present anywhere else?

2024-12-13 10:15 UTC, WiserTixx commented on ui/modModules/multiplayer/direct.partial.html
> +		<md-button id="add-fav-button" class="button" ng-click="multiplayer.directConnectFavorite()" tabindex="4">{{:: 'ui.multiplayer.add.favorite' | translate}}</md-button>
Please revert this as the new translation key isn't present in english.

2024-12-13 10:15 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +  background-color: rgba(0, 0, 0, 0.4); /* новый */
Could this be in english?

2024-12-13 10:15 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +  background-color: rgba(0, 0, 0, 0.4); /* новый */
Could this be in english?

2024-12-13 10:15 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +                                                                                                /*новое - покачто не используется */
Could this be in english?

2024-12-13 10:15 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +  width: 400px; /* новый */
Could this be in english?

2024-12-13 10:15 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +  width: auto; /* новый */
Could this be in english?

2024-12-13 10:15 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +  min-width: 400px;
Could this be in english?

2024-12-13 10:15 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +
What is this?

2024-12-13 11:10 UTC, csv4211 commented on ui/modModules/multiplayer/multiplayer.css
> +  background-color: rgba(0, 0, 0, 0.4); /* новый */
These are the marks that I left about the old and new parameters, if they are important, I can translate them into English or remove them

2024-12-13 11:16 UTC, csv4211 commented on ui/modModules/multiplayer/direct.partial.html
> +		<md-button id="add-fav-button" class="button" ng-click="multiplayer.directConnectFavorite()" tabindex="4">{{:: 'ui.multiplayer.add.favorite' | translate}}</md-button>
in en.json there is a key "ui.multiplayer.favorite" it is translated as "ui.multiplayer.add.favorite", you can change the key in en.json and the rest where it is present, or leave it as "ui.multiplayer.favorite "

2024-12-13 11:18 UTC, WiserTixx commented on ui/modModules/multiplayer/direct.partial.html
> +		<md-button id="add-fav-button" class="button" ng-click="multiplayer.directConnectFavorite()" tabindex="4">{{:: 'ui.multiplayer.add.favorite' | translate}}</md-button>
I'd prefer to leave it as "ui.multiplayer.favorite".

2024-12-13 11:21 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +  background-color: rgba(0, 0, 0, 0.4); /* новый */
What do they say? If it's just old and new please remove them and the old code as well.

2024-12-13 11:22 UTC, csv4211 commented on ui/modModules/multiplayer/multiplayer.css
> +  background-color: rgba(0, 0, 0, 0.4); /* новый */
ok

2024-12-13 11:28 UTC, csv4211 reviewed
"ui.multiplayer.add.favorite" changed to "ui.multiplayer.favorite"
unnecessary tags removed

2024-12-15 21:17 UTC, csv4211 reviewed
.

2024-12-17 17:58 UTC, Starystars67 requested changes

2024-12-17 17:58 UTC, Starystars67 commented on mp_locales/en-US.json
> +    "ui.mainmenu.mod": "Mod",
Line not required anymore as of 0.34.2.
Please remove.

2024-12-17 17:58 UTC, Starystars67 commented on mp_locales/ru_RU.json
> +  "ui.mainmenu.mod": "Мод",
Still needed as not included with the game translation yet.

2024-12-17 17:58 UTC, Starystars67 commented on ui/modModules/multiplayer/direct.partial.html
> +			<md-button class="paste-from-clipboard-but" ng-class="" ng-click="multiplayer.pasteClipboardToDirectIP()">{{:: 'ui.multiplayer.pasteFromClipboard' | translate}}</md-button>
How come you do not use the button class still here?

2024-12-17 18:30 UTC, csv4211 commented on ui/modModules/multiplayer/direct.partial.html
> +			<md-button class="paste-from-clipboard-but" ng-class="" ng-click="multiplayer.pasteClipboardToDirectIP()">{{:: 'ui.multiplayer.pasteFromClipboard' | translate}}</md-button>
if I leave the "button" class and change the "servers-button" class to another one with the necessary styles, the button stretches to the entire screen because in the "button" class there is a style "width: 100%" which stretches the button and I need to change this style this may break other buttons, so I added a separate class with all the necessary styles
![image](https://github.com/user-attachments/assets/a1ef7cfe-06de-4466-8e6d-96919d717670)
![image](https://github.com/user-attachments/assets/4c7d8b6c-3287-4491-bd8d-12034d9a3438)
![image](https://github.com/user-attachments/assets/ff8ef2d9-f829-487f-a15c-ffb27f3b8ae5)

2024-12-17 18:36 UTC, csv4211 commented on ui/modModules/multiplayer/direct.partial.html
> +			<md-button class="paste-from-clipboard-but" ng-class="" ng-click="multiplayer.pasteClipboardToDirectIP()">{{:: 'ui.multiplayer.pasteFromClipboard' | translate}}</md-button>
Even if set a fixed width in the "paste-from-clipboard-but" class, it is still interrupted by the "button" class

2024-12-17 18:39 UTC, csv4211 commented on mp_locales/ru_RU.json
> +  "ui.mainmenu.mod": "Мод",
done, line 4 deleted

2024-12-17 18:39 UTC, csv4211 commented on mp_locales/en-US.json
> +    "ui.mainmenu.mod": "Mod",
done, line 4 deleted

2024-12-19 12:32 UTC, csv4211 reviewed
ᅠ ᅠ

2024-12-19 22:04 UTC, WiserTixx commented
Could the merge conflicts be resolved?

2024-12-19 22:11 UTC, closed without merging