little changed UI
Starystars67/BeamNG-MP pull request #683
Opened 2024-12-20 00:52 UTC by csv4211

Fork updated

2024-12-20 00:52 UTC, csv4211 commented
sorry accidentally closed the last PR

2024-12-21 19:41 UTC, WiserTixx requested changes

2024-12-21 19:41 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +}
I'd prefer to not have such generic styles, this might have impact on a game element somewhere which I'd like to avoid.

2024-12-21 19:41 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +  width: auto;
Are there meant to be 2 width values here?

2024-12-21 19:49 UTC, csv4211 commented on ui/modModules/multiplayer/multiplayer.css
> +  width: auto;
fix it now, line 68 shouldn't have been there

2024-12-21 19:58 UTC, csv4211 commented on ui/modModules/multiplayer/multiplayer.css
> +}
I made a mistake, there should be classes ".md-button.md-primary.md-raised" and ".md-button.md-primary.md-raised:not([disabled]):hover"

2024-12-21 20:37 UTC, csv4211 commented on ui/modModules/multiplayer/multiplayer.css
> +}
I tried to get rid of such common styles, but the direct button goes as an <a> element and not as an <md-button>, which is why I have to use the style "a.md-button.md-primary.md-raised: not([disabled]):hover" instead of ".md-button.md-primary.md-raised:not([disabled]):hover" - which matches the rest of the buttons,
I tried to add a separate class for the direct connection button, but its background still did not change when activated

2024-12-24 10:37 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +}
Okay, and why did you make this change? Testing the buttons myself they seem to all act the same way.

2024-12-25 17:26 UTC, csv4211 commented on ui/modModules/multiplayer/multiplayer.css
> +}
![image](https://github.com/user-attachments/assets/dec56426-74c7-405c-9399-e7903123a5d3)
in the first screenshot these styles are indicated 
`
a.md-button.md-primary.md-raised, .md-button.md-primary.md-raised {
  background-color: rgba(27,27,27,0.3);
}

a.md-button.md-primary.md-raised:not([disabled]):hover, .md-button.md-primary.md-raised:not([disabled]):hover { 
  background-color: rgba(27,27,27,0.4);
}
`

![image](https://github.com/user-attachments/assets/3083bc50-5504-4839-b13d-2d270084835b)
and on the second one such 
`
.md-button.md-primary.md-raised {
  background-color: rgba(27,27,27,0.3);
}

.md-button.md-primary.md-raised:not([disabled]):hover { 
  background-color: rgba(27,27,27,0.4);
}
`

maybe it's just me who has some bugs, but it should be like in the first screenshot

2025-01-11 16:38 UTC, WiserTixx commented on ui/modModules/multiplayer/multiplayer.css
> +}
Why should it be like the first one?

2025-01-11 16:40 UTC, WiserTixx commented
It looks like you've changed a few colours, are those all stylistic changes?

2025-01-11 20:39 UTC, closed without merging